### ISSUE TITLE
Why not local to local ?

### ISSUE THREAD

**Issue by tst2005** [josephernest/nfreezer#16]
Hello,

I'm already using rclone, syncthing, duplicity, rsync, encfs, ...
I discovered nfreezer, It seems very interessting!

I started a simple test on my local laptop...
Sadly It seems impossible to make a simple local to local backup (`nfreezer backup foo/ /tmp/bar/`)
I used `nfreezer foo/ ${USER}@localhost:/tmp/bar/`.
Is there a technical reason ?

For now it is just a test, but even in production, I will need a local to local backup.
In my case, we send copies on multiple remote storage, so we prefere doing the encryption once localy and send copies independantly of the encryption tool.
The remotes target are synchronized with another way (mainly rsync) with specific bandwith and time constraint.

Do you think local to local backup is hard to support ?

**Comment by josephernest** [comment]
Thank you for your feebback @tst2005.

Yes, local to local is on the roadmap - I have been busy the past months, so I'll look a bit later, but it is definitely something that will be added.
