### ISSUE TITLE
Permission error during backup

### ISSUE THREAD

**Issue by kryst3q** [josephernest/nfreezer#7]
Hello. First, thank you very much for such small and useful piece of code. I have one problem. I installed nfreezer on Ubuntu Server 20.04 using pip3 (pip 20.0.2 (python 3.8)). And when I try to create backup on remote server I got the following error:

```
Please enter the encryption password:
Distant files list: getting...
Distant files list: done.
Traceback (most recent call last):
  File "./.local/bin/nfreezer", line 8, in <module>
    sys.exit(console_script())
  File "/home/kryst3q/.local/lib/python3.8/site-packages/nfreezer.py", line 262, in console_script
    backup(src=sys.argv[2], dest=sys.argv[3])
  File "/home/kryst3q/.local/lib/python3.8/site-packages/nfreezer.py", line 181, in backup
    h = getsha256(fn)
  File "/home/kryst3q/.local/lib/python3.8/site-packages/nfreezer.py", line 31, in getsha256
    with open(f, 'rb') as g:
PermissionError: [Errno 13] Permission denied: 'rsa_key.der'
```

On target server the only file that is created is `.files`. Probably I'm doing something wrong but I don't know what.

**Comment by josephernest** [comment]
Thanks for your feedback @kryst3q.

This happens during the scanning of local files.

It seems that your current unix user does not have the rights to read one file named `rsa_key.der`. People seem to have a similar problem here https://github.com/dani-garcia/bitwarden_rs/issues/366.

Can you do `ls -la /path/to/your/rsa_key.der` and copy/paste the result?

What happens if you use `sudo`? 
Instead of doing `nfreezer ...`, you can try `sudo nfreezer ...`.

**Comment by kryst3q** [comment]
Wow @josephernest thanks for super fast reply! You were right. It was file owning rights issue. The `ls -la` command returned info that files I wanted to backup were owned by root.
```
total 388K
drwxrwxr-x 3 kryst3q kryst3q 4.0K Dec 15 13:10 .
drwxrwxr-x 3 kryst3q kryst3q 4.0K Dec  5 23:07 ..
-rw-r--r-- 1 root    root    1.1K Dec  5 23:16 config.json
-rw-r--r-- 1 root    root    316K Dec 15 12:37 db.sqlite3
-rw-r--r-- 1 root    root     32K Dec 15 13:10 db.sqlite3-shm
-rw-r--r-- 1 root    root    8.1K Dec 15 13:10 db.sqlite3-wal
drwxr-xr-x 2 root    root    4.0K Dec 14 23:59 icon_cache
-rw------- 1 root    root    1.2K Dec  5 23:07 rsa_key.der
-rw------- 1 root    root    1.7K Dec  5 23:07 rsa_key.pem
-rw-r--r-- 1 root    root     270 Dec  5 23:07 rsa_key.pub.der
```
I can't change this. So the things I had to do were installing nfreezer globally (`sudo pip3 -H install nfreezer`) and execute backup command using `sudo`. After that everything worked like a charm. Many thanks again!
